import type { Metadata } from 'next';
import './globals.css';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<link
					rel='stylesheet'
					as='style'
					href='https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css'
				/>
			</head>

			<body className={`antialiased font-pretendard flex flex-col min-h-screen`}>
				<header className='flex flex-row gap-4 justify-between items-center px-16 py-4 bg-white dark:bg-black sticky top-0 z-10'>
					<Link href='/'><img src="/icon.svg" alt="logo" className='w-10 h-10' /></Link>
					<div>
						<Button variant="link" asChild className="text-md"><Link href='/posts'>POSTS</Link></Button>
						<Button variant="link" asChild className="text-md"><Link href='/resume'>RESUME</Link></Button></div>
				</header>

				<main className='flex-1'>{children}</main>

				<footer className='flex flex-row gap-4 justify-between px-16 py-4 bg-white dark:bg-black'>
					<p>© 2026 Jina Cheon. All rights reserved.</p>
				</footer>
			</body>

		</html>
	);
}
